In [1]:
words = open('names.txt', 'r').read().splitlines()

In [2]:
words[:10]

['emma',
 'olivia',
 'ava',
 'isabella',
 'sophia',
 'charlotte',
 'mia',
 'amelia',
 'harper',
 'evelyn']

In [3]:
letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z','.']
b = {}




for w in words:
    chs = ['.'] + list(w) + ['.']
    for ch1,ch2,ch3 in zip(chs,chs[1:],chs[2:]):
        trigram = (ch1,ch2,ch3)
        b[trigram] = b.get(trigram,0) + 1


In [4]:
sorted(b.items(),key = lambda kv: -kv[1])

[(('a', 'h', '.'), 1714),
 (('n', 'a', '.'), 1673),
 (('a', 'n', '.'), 1509),
 (('o', 'n', '.'), 1503),
 (('.', 'm', 'a'), 1453),
 (('.', 'j', 'a'), 1255),
 (('.', 'k', 'a'), 1254),
 (('e', 'n', '.'), 1217),
 (('l', 'y', 'n'), 976),
 (('y', 'n', '.'), 953),
 (('a', 'r', 'i'), 950),
 (('i', 'a', '.'), 903),
 (('i', 'e', '.'), 858),
 (('a', 'n', 'n'), 825),
 (('e', 'l', 'l'), 822),
 (('a', 'n', 'a'), 804),
 (('i', 'a', 'n'), 790),
 (('m', 'a', 'r'), 776),
 (('i', 'n', '.'), 766),
 (('e', 'l', '.'), 727),
 (('y', 'a', '.'), 716),
 (('a', 'n', 'i'), 703),
 (('.', 'd', 'a'), 700),
 (('l', 'a', '.'), 684),
 (('e', 'r', '.'), 683),
 (('i', 'y', 'a'), 669),
 (('l', 'a', 'n'), 647),
 (('.', 'b', 'r'), 646),
 (('n', 'n', 'a'), 633),
 (('.', 'a', 'l'), 632),
 (('.', 'c', 'a'), 628),
 (('r', 'a', '.'), 627),
 (('n', 'i', '.'), 625),
 (('.', 'a', 'n'), 623),
 (('n', 'n', '.'), 619),
 (('n', 'e', '.'), 607),
 (('e', 'e', '.'), 605),
 (('e', 'y', '.'), 602),
 (('.', 'k', 'e'), 601),
 (('a', 'l', 'e')

In [5]:
import torch

In [6]:
chars = sorted(list(set(''.join(words))))
stoi = {s:i+1 for i,s in enumerate(chars)}
stoi['.'] = 0
itos = {i:s for s,i in stoi.items()}

In [7]:
itos

{1: 'a',
 2: 'b',
 3: 'c',
 4: 'd',
 5: 'e',
 6: 'f',
 7: 'g',
 8: 'h',
 9: 'i',
 10: 'j',
 11: 'k',
 12: 'l',
 13: 'm',
 14: 'n',
 15: 'o',
 16: 'p',
 17: 'q',
 18: 'r',
 19: 's',
 20: 't',
 21: 'u',
 22: 'v',
 23: 'w',
 24: 'x',
 25: 'y',
 26: 'z',
 0: '.'}

In [8]:
N = torch.zeros((27, 27,27), dtype=torch.int32)


In [9]:
for w in words:
  chs = ['.'] + list(w) + ['.']
  for ch1, ch2, ch3 in zip(chs, chs[1:],chs[2:]):
    ix1 = stoi[ch1]
    ix2 = stoi[ch2]
    ix3 = stoi[ch3]
    N[ix1, ix2,ix3] += 1 

In [10]:
N

tensor([[[  0,   0,   0,  ...,   0,   0,   0],
         [  0, 207, 190,  ...,  27, 173, 152],
         [  0, 169,   0,  ...,   0,   4,   0],
         ...,
         [  0,  57,   0,  ...,   1,  17,  11],
         [  0, 246,   0,  ...,   0,   0,   2],
         [  0, 456,   0,  ...,   0,  91,   1]],

        [[  0,   0,   0,  ...,   0,   0,   0],
         [ 40,   0,   5,  ...,   0,  20,  11],
         [ 36,  28,  20,  ...,   0,  12,   0],
         ...,
         [ 11,   5,   0,  ...,  17,   6,   3],
         [163, 389,  13,  ...,   0,  16,  40],
         [ 38, 123,   0,  ...,   0,  12,  22]],

        [[  0,   0,   0,  ...,   0,   0,   0],
         [ 46,   5,   5,  ...,   4,  31,   4],
         [  1,   8,   0,  ...,   0,   9,   0],
         ...,
         [  0,   0,   0,  ...,   0,   0,   0],
         [ 55,   4,   1,  ...,   0,   0,   0],
         [  0,   0,   0,  ...,   0,   0,   0]],

        ...,

        [[  0,   0,   0,  ...,   0,   0,   0],
         [ 10,   0,   2,  ...,   0,  10,   0]

In [11]:
# import matplotlib.pyplot as plt                           
# %matplotlib inline

# N_2d  = torch.zeros((729,27), dtype=torch.int32)

# plt.figure()
# plt.imshow(N_2d, cmap='Blues')
# for i in range(729):
#     for j in range(27):
#             chstr = itos[i] + itos[j] 
#             plt.text(j, i, chstr, ha="center", va="bottom", color='gray')
#             plt.text(j, i, N[i, j].item(), ha="center", va="top", color='gray')
# plt.axis('off');


In [12]:
# # importing mplot3d toolkits, numpy and matplotlib
# from mpl_toolkits import mplot3d
# import numpy as np
# import matplotlib.pyplot as plt

# fig = plt.figure()

# # syntax for 3-D projection
# ax = plt.axes(projection ='3d')

# # defining all 3 axis
# z = np.linspace(0, 1, 100)
# x = z * np.sin(25 * z)
# y = z * np.cos(25 * z)

# # plotting
# ax.plot3D(x, y, z, 'green')
# ax.set_title('3D line plot geeks for geeks')
# plt.show()




In [13]:
g = torch.Generator().manual_seed(2147483647)
p = torch.rand(3, generator=g)          # The probability is deterministic by the seed
p = p / p.sum()
p                  

tensor([0.6064, 0.3033, 0.0903])

In [14]:
p = N[0][1].float()
p = p / p.sum()
p

tensor([0.0000, 0.0469, 0.0431, 0.0070, 0.0830, 0.0125, 0.0048, 0.0039, 0.0206,
        0.0349, 0.0061, 0.0170, 0.1433, 0.0871, 0.1413, 0.0023, 0.0039, 0.0020,
        0.1093, 0.0440, 0.0163, 0.0345, 0.0551, 0.0014, 0.0061, 0.0392, 0.0345])

In [15]:
P = (N+1).float()
P /= P.sum(2,keepdim=True)
P

tensor([[[3.7037e-02, 3.7037e-02, 3.7037e-02,  ..., 3.7037e-02,
          3.7037e-02, 3.7037e-02],
         [2.2538e-04, 4.6879e-02, 4.3047e-02,  ..., 6.3106e-03,
          3.9216e-02, 3.4483e-02],
         [7.5019e-04, 1.2753e-01, 7.5019e-04,  ..., 7.5019e-04,
          3.7509e-03, 7.5019e-04],
         ...,
         [6.2112e-03, 3.6025e-01, 6.2112e-03,  ..., 1.2422e-02,
          1.1180e-01, 7.4534e-02],
         [1.7794e-03, 4.3950e-01, 1.7794e-03,  ..., 1.7794e-03,
          1.7794e-03, 5.3381e-03],
         [1.0460e-03, 4.7803e-01, 1.0460e-03,  ..., 1.0460e-03,
          9.6234e-02, 2.0921e-03]],

        [[3.7037e-02, 3.7037e-02, 3.7037e-02,  ..., 3.7037e-02,
          3.7037e-02, 3.7037e-02],
         [7.0326e-02, 1.7153e-03, 1.0292e-02,  ..., 1.7153e-03,
          3.6021e-02, 2.0583e-02],
         [6.5141e-02, 5.1056e-02, 3.6972e-02,  ..., 1.7606e-03,
          2.2887e-02, 1.7606e-03],
         ...,
         [5.7416e-02, 2.8708e-02, 4.7847e-03,  ..., 8.6124e-02,
          3.349

In [16]:
tmp = 0
for i in range(27):
    tmp += P[1][3][i] 
tmp

tensor(1.)

In [17]:
g = torch.Generator().manual_seed(2147483647)

ix = 0 

# First has to be '.'
# second is mostly 'a'

for j in range(100):
  out = ['.','a'] # this could be fixed
  fs = 0
  sc = 1
  while True:
    p = P[fs][sc]
    ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
    out.append(itos[ix])
    fs = sc 
    sc = ix
    if ix == 0:
      break
  print(''.join(out))

.aluwjde.
.ailyasid.
.aurelay.
.aadin.
.avon.
.arltoper.
.amaree.
.aviahnia.
.avinileniassibduinrwin.
.alessiyanayla.
.are.
.aunviumthyfortumj.
.an.
.ann.
.alena.
.amani.
.arose.
.aya.
.anocken.
.avandreerimouis.
.ayn.
.an.
.aanaasnhavi.
.amonszxhddion.
.amithani.
.az.
.arie.
.ann.
.arystin.
.anrsli.
.aish.
.aubri.
.ammel.
.am.
.amah.
.aubwyla.
.avan.
.amia.
.ar.
.aydnh.
.additta.
.amalyn.
.abel.
.ah.
.aur.
.alavarocbzthemiraya.
.art.
.an.
.avon.
.am.
.alivisotten.
.asalee.
.amarlen.
.alianabethellianten.
.anix.
.amura.
.aodridyden.
.anialiypvrgia.
.atezrwaylia.
.avywhqelvani.
.alahimah.
.aurik.
.amil.
.an.
.assabdon.
.aurne.
.alian.
.adenn.
.as.
.ayannyah.
.ann.
.arvjynkmarianner.
.asiah.
.aan.
.akly.
.aderihana.
.aniday.
.avidon.
.abasstertte.
.azeus.
.adasia.
.an.
.attalyndrishanido.
.aklealilondral.
.afinmari.
.am.
.ashama.
.averykongeon.
.ardiyahvion.
.augus.
.amogtjvnvigh.
.ark.
.aurrafelanaylian.
.ayhgnorrisyli.
.arsonridertimarkenniyaneria.
.amiel.
.al.
.alicvatavryaaleximrla.
